import { useState } from 'react'
import {
  Badge,
  DataCard,
  Inline,
  PageHeader,
  Stack,
  Tabs,
  Text,
} from '@deliverect/galaxy-react'
import { Page } from '../components/Page'
import { AgentsTable } from '../components/AgentsTable'
import { ActivityLog } from '../components/ActivityLog'
import { MOCK_LOGS } from '../data/mockLogs'
import { vars } from '@deliverect/galaxy-react'

// ─── DataCards ────────────────────────────────────────────────────────────────

function SummaryCards() {
  return (
    <Inline space="150" width="full">
      <DataCard.Root flex={1}>
        <DataCard.Header>
          <DataCard.Title tooltip="Total number of changes made by all agents">Total actions</DataCard.Title>
        </DataCard.Header>
        <DataCard.Content>
          <Inline space="100" alignY="center">
            <DataCard.Value>2,900</DataCard.Value>
            <DataCard.ChangeIndicator relativeChange={12}>+12%</DataCard.ChangeIndicator>
          </Inline>
          <Text color="secondary" size="sm">vs. last period</Text>
        </DataCard.Content>
      </DataCard.Root>

      <DataCard.Root flex={1}>
        <DataCard.Header>
          <DataCard.Title tooltip="Number of locations affected by agent actions">Locations impacted</DataCard.Title>
        </DataCard.Header>
        <DataCard.Content>
          <Inline space="100" alignY="center">
            <DataCard.Value>850</DataCard.Value>
            <DataCard.ChangeIndicator relativeChange={5}>+5%</DataCard.ChangeIndicator>
          </Inline>
          <Text color="secondary" size="sm">vs. last period</Text>
        </DataCard.Content>
      </DataCard.Root>

      <DataCard.Root flex={1}>
        <DataCard.Header>
          <DataCard.Title tooltip="Estimated additional revenue generated by agent optimisations">Revenue uplift</DataCard.Title>
        </DataCard.Header>
        <DataCard.Content>
          <Inline space="100" alignY="center">
            <DataCard.Value>$1,500</DataCard.Value>
            <DataCard.ChangeIndicator relativeChange={8}>+8%</DataCard.ChangeIndicator>
          </Inline>
          <Text color="secondary" size="sm">vs. last period</Text>
        </DataCard.Content>
      </DataCard.Root>

      <DataCard.Root flex={1}>
        <DataCard.Header>
          <DataCard.Title tooltip="Estimated revenue protected by agent interventions">Revenue loss prevented</DataCard.Title>
        </DataCard.Header>
        <DataCard.Content>
          <Inline space="100" alignY="center">
            <DataCard.Value>$1,500</DataCard.Value>
            <DataCard.ChangeIndicator relativeChange={3}>+3%</DataCard.ChangeIndicator>
          </Inline>
          <Text color="secondary" size="sm">vs. last period</Text>
        </DataCard.Content>
      </DataCard.Root>
    </Inline>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

export function AIHomeBPage() {
  const [activeTab, setActiveTab] = useState('overview')

  return (
    <Page.Root>
      <PageHeader.Header px="300" py="200" space="100" alignY="center" style={{ flexShrink: 0 }}>
        <Inline space="100" alignY="center">
          <PageHeader.Title>Deliverect AI</PageHeader.Title>
          <Badge size="sm" status="info">Beta</Badge>
        </Inline>
      </PageHeader.Header>

      <div style={{ paddingLeft: vars.spacing['300'] }}>
        <Tabs.Root value={activeTab} onValueChange={setActiveTab}>
          <Tabs.List>
            <Tabs.Trigger value="overview">Overview</Tabs.Trigger>
            <Tabs.Trigger value="activity">Activity</Tabs.Trigger>
          </Tabs.List>
        </Tabs.Root>
      </div>

      <Page.Body space="250" py="250">
        {activeTab === 'overview' && (
          <>
            <SummaryCards />

            <Stack height="auto" space="150">
              <Text weight="bold">My agents</Text>
              <AgentsTable />
            </Stack>
          </>
        )}

        {activeTab === 'activity' && (
          <ActivityLog logs={MOCK_LOGS} showAgentColumn showAgentTypeFilter />
        )}
      </Page.Body>
    </Page.Root>
  )
}
